version: '3.8'

services:
 app:
  build: .
  command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0:8000"
  container_name: testcontainer
  ports:
   - "8000:8000"

#Docker-Compose can always invoke a Dockerfile when using the build parameter.